version: 2
jobs:
  test-job:
    working_directory: ~/alberii/rose
    docker:
      - image: avcosystems/golang-node

    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: npm run lint
          command: npm run lint
      - run:
          name: npm test
          command: npm test

  deploy-job:
    working_directory: ~/alberii/rose
    docker:
      - image: python

    steps:
      - checkout
      - run:
          name: install awsebcli
          command: pip install awsebcli
      - run:
          name: deploy
          command: eb deploy s-port-dev

workflows:
  version: 2
  build-deploy:
    jobs:
      - test-job
      - deploy-job:
          requires:
            - test-job
          filters:
            branches:
              only: master
